workflow/urls.py
from django.urls import path
from . import views,workflow


urlpatterns = [

    path('addworkflow/',views.workflowpro,name='addworkflow'),
    path('editworkflow//<int:pk>/',views.editworkflow,name='editworkflow'),
    path('workflowlist/',views.workflowlist,name='workflowlist'),
    path('a/',views.GetModelFieldsByAppName),
    path('logicworkflow/',views.workflowlogic,name='logicworkflow'),

    path('approver_list/', views.approver_list, name='approver_list'),
    path('add_approver/', views.add_approver, name='add_approver'),
    path('edit_approver/<int:pk>/', views.edit_approver, name='edit_approver'),
    path('delete_approver/<int:pk>/', views.delete_approver, name='delete_approver'), 
    #path('mydocuments/',workflow.mydocuments,name="mydocuments"),
    path('mydocuments/',workflow.mydocuments,name='mydocuments'),
   
]

workflow/models.py
from django.db import models
from administration.models import Users,Applications,Processes
from checklists.Logdata import logdata

class workflow(models.Model):
    WF_ID = models.AutoField(primary_key=True)
    AppID = models.CharField(max_length=50,null=True,blank=True) # remove
    AppName = models.CharField(max_length=50,null=True,blank=True) # remove
    ProcessID = models.IntegerField(default=1)
    ProcessName = models.ForeignKey(Processes,on_delete=models.CASCADE,default=1)
    Main_model = models.CharField(max_length=50,null=True,blank=True)
    para_1 = models.CharField(max_length=50,null=True,blank=True)
    value_1 = models.CharField(max_length=50,null=True,blank=True)
    para_2 = models.CharField(max_length=50,null=True,blank=True)
    value_2 = models.CharField(max_length=50,null=True,blank=True)
    para_3 = models.CharField(max_length=50,null=True,blank=True)
    value_3 = models.CharField(max_length=50,null=True,blank=True)
    para_4 = models.CharField(max_length=50,null=True,blank=True)
    value_4 = models.CharField(max_length=50,null=True,blank=True)
    para_5 = models.CharField(max_length=50,null=True,blank=True)
    value_5 = models.CharField(max_length=50,null=True,blank=True)
    User_names = models.JSONField(default=list)

    def save(self, *args, **kwargs):
         logdata('record....!')
         logdata(self.ProcessName)
         self.ProcessID = self.ProcessName.ProcessID 
         super().save(*args, **kwargs) 
         return

    def __str__(self):
        return str(self.AppName)
    
class WorkflowLOG(models.Model):
    LogID = models.AutoField(primary_key=True) 
    WF_ID = models.CharField(max_length=70)
    Doc_ID = models.CharField(max_length=70)    # Example Vendor Id
    AppID = models.CharField(max_length=70) 
    AppName = models.CharField(max_length=70)
    ProcessID = models.IntegerField()
    ProcessName = models.CharField(max_length=100)
    CurrentUser = models.CharField(max_length=70) 
    NextUser = models.CharField(max_length=500) 
    Action = models.CharField(max_length=70) 
    DateTimeStamp = models.DateTimeField(auto_now_add=True)
    Comment = models.CharField(max_length=100,null=True,blank=True)


    def __str__(self):
        return str(self.LogID)

class WorkflowInbox(models.Model):
    inbox_id = models.AutoField(primary_key=True)
    Doc_ID = models.CharField(max_length=70)  
    AppID = models.CharField(max_length=70) 
    ProcessID = models.IntegerField()
    CurrentUser = models.CharField(max_length=70) 
    NextUser = models.CharField(max_length=500)
    DateTimeStamp = models.DateTimeField(auto_now_add=True) 


class Approver(models.Model): 
     ApproverID = models.AutoField(primary_key=True)
     ApproverDescription = models.CharField(max_length=100, default='')
     User = models.ForeignKey(Users,on_delete=models.CASCADE)

     def __str__(self):
         return self.ApproverID

workflow/templates/workflow/MyDocument.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} 
   {{ page_title }}
{% endblock title %}

{% block formcontent %}
{% if form %}
<div class="text-center">
  <h2 style="color:darkcyan;font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;"> {{ app_title }} </h2></div>
  <form method="POST">
      {% csrf_token %}
      {{ form | crispy }}
      <button type="submit" class="btn-primary" style="padding-left:10px;padding-right: 10px;">Save</button>
  </form>
</div>
{% else %}
  
{% endif %}
<div class="container-fluid">
<div class="row">
    <div class="container-fluid">
            {% if workflow_info %}
            <br>
            <h3>List of Inbox Documents</h3>
            <div>
                <table class="table table-hover table-responsive-md table-bordered" style="font-size: 10px;">
                    <thead>
                        <tr>
                            <th class="custom-th" scope="col">Doc ID</th>
                            <th class="custom-th" scope="col">Process Name</th>
                            <th class="custom-th" scope="col">Previous User</th>
                            <th class="custom-th" scope="col">Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for docu in workflow_info %}
                        <tr onclick="window.location='{{ docu.url }}';" style="cursor: pointer;">
                            <td class="custom-td" scope="row">{{ docu.Doc_ID }}</td>
                            <td class="custom-td">{{ docu.ProcessName }}</td>
                            <td class="custom-td">{{ docu.CurrentUser }}</td>
                            <td class="custom-td">{{ docu.DateTimeStamp }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
           
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

workflow/templates/workflow/approver.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} 
   {{ page_title }}
{% endblock title %}

{% block formcontent %}
  {% if form %}
    <div class="text-center">
      <h2 style="color:darkcyan;font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;"> {{ app_title }} </h2></div>
      <form method="POST">
          {% csrf_token %}
          {{ form | crispy }}
          <button type="submit" class="btn-primary" style="padding-left:10px;padding-right: 10px;">Save</button>
      </form>
    </div>
  {% else %}
    <a type="button" class="btn btn-primary" href="{% url 'add_approver' %}" style="margin-left:15px;">Create</a>
  {% endif %}
  <div class="container-fluid">
    <div class="row">
      <div class="container-fluid">
          {% if approvers %}
          <br>
          <h3>List of Approvers</h3>
          <div>
            <table class="table table-hover table-responsive-md table-bordered" style="font-size: 10px;">
                <thead>
                  <tr>
                    <th class="custom-th" scope="col">Approval ID</th>
                    <th class="custom-th" scope="col">Approval Description</th>
                    <th class="custom-th" scope="col">User ID</th>
                    <th class="custom-th" scope="col">Username</th>
                    <th class="custom-th" scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for approver in approvers %}
                  <tr>
                    <td class="custom-td" scope="row">{{approver.ApproverID}}</td>
                    <td class="custom-td">{{approver.ApproverDescription}}</td>
                    <td class="custom-td">{{approver.User.UserID}}</td>
                    <td class="custom-td">{{approver.User.username}}</td>
                    <td class="custom-td">
                        <a type="button" class="btn btn-primary" href="{% url 'edit_approver' approver.ApproverID %}" style="padding-left:10px;padding-right: 10px;">Edit</a>
                        <a type="button" class="btn btn-danger" href="{% url 'delete_approver' approver.ApproverID %}" style="padding-left:10px;padding-right: 10px;">Delete</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
            </table>
          <div>
          {% else %}
              <h4 class="text-center alert alert-warning" style="font-size: 14px;">No approval available</h4>
          {% endif %}
          </div>
      </div>
    </div>
  </div>
{% endblock %}
 

workflow/templates/workflow/workflow-backup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    {{ page_title }}
{% endblock title %}

{% block formcontent %}
{% if form %}
<div class="text-center">
  <h2 style="color:darkcyan;font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;"> {{ app_title }} </h2></div>
<form method="post" id="workflow-form">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <div class="row">
      
        <div class="col-md-12 text-left">
          {{ form.ProcessName|as_crispy_field }}
        </div>
        
       </div>
          <div class="row">
          <div class="col-md-6 text-left">
            {{ form.para_1|as_crispy_field }}
            <!-- <select name="para_11" id="id_para_11" class="form-control"></select> -->
          </div>
          <div class="col-md-6 text-left">
            {{ form.value_1|as_crispy_field }}
          </div></div>
          
          <div class="row">
            <div class="col-md-6 text-left">
              {{ form.para_2|as_crispy_field }}
              <!-- <select name="para_22" id="id_para_22" class="form-control"></select> -->
              
            </div>
            <div class="col-md-6 text-left">
              {{ form.value_2|as_crispy_field }}

            </div></div>
            <div class="row">
                <div class="col-md-6 text-left">
                  {{ form.para_3|as_crispy_field }}
                  <!-- <select name="para_33" id="id_para_33" class="form-control"></select> -->
                </div>
                <div class="col-md-6 text-left">
                  {{ form.value_3|as_crispy_field }}
                </div></div>
                <div class="row">
                    <div class="col-md-6 text-left">
                      {{ form.para_4|as_crispy_field }}
                      <!-- <select name="para_44" id="id_para_44" class="form-control"></select> -->
                    </div>
                    <div class="col-md-6 text-left">
                      {{ form.value_4|as_crispy_field }}
                    </div></div>
                    <div class="row">
                        <div class="col-md-6 text-left">
                          {{ form.para_5|as_crispy_field }}
                          <!-- <select name="para_55" id="id_para_55" class="form-control"></select> -->

                        </div>
                        <div class="col-md-6 text-left">
                          {{ form.value_5|as_crispy_field }}
                        </div></div>
                        <div class="row">
                            <div class="col-6">
                                {{ form.User_names|as_crispy_field }}
                            </div>
                        </div>

    <button type="submit">Submit</button>
  </form>
  {% else %}
    <a type="button" class="btn btn-primary" href="{% url 'addworkflow' %}" style="margin-left:15px;">Create</a>
  {% endif %}
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

  <!-- <script>

    document.addEventListener("DOMContentLoaded", function () {

        $("#id_AppName").change(function () {
            var application_nameId = this.value;  // Correct variable name
            // console.log(application_nameId);

            $.ajax({
                type: "POST",
                url: '{% url "get_model_ajax" %}',
                data: {
                    'application_nameId': application_nameId,
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                },
                success: function (data) {
                    if ('error_message' in data) {
                        console.error(data.error_message);
                    } else {
                        // console.log(data.model_name);
                        document.getElementById("id_Main_model").value =data.model_name ;
                        var NameModel=data.model_name
                        AotoFields(application_nameId,NameModel);
                    }
                }
            });
  
        });

        // AppID GOT
        $("#id_AppName").change(function () {
            var application_nameId = this.value;  // Correct variable name
            // console.log(application_nameId);

            $.ajax({
                type: "POST",
                url: '{% url "get_appid_ajax" %}',
                data: {
                    'application_nameId': application_nameId,
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                },
                success: function (data) {
                    if ('error_message' in data) {
                        console.error(data.error_message);
                    } else {
                        // console.log(data.model_name);
                        document.getElementById("id_AppID").value =data.AppID ;
                        var appid=data.AppID
                        AotoFields(application_nameId,appid);
                    }
                }
            });
  
        });
    }
    )
</script> -->
<!-- <script>
     function AotoFields(application_nameId,NameModel){
            // var mainModelName = this.value;
            var a = document.getElementById('id_application_name').value;
            console.log(NameModel)
            $.ajax({
                type: "POST",
                url: '{% url "get_fields_ajax" %}',
                data: {
                    'application_nameId':application_nameId,
                    'NameModel': NameModel,
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                },
              
                success: function (data) {
                    let listid = ['id_para_11', 'id_para_22', 'id_para_33','id_para_44','id_para_55'];
                 
                    listid.forEach(function (id) {
                        var dropdown = document.getElementById(id);
                        dropdown.innerHTML = '';

                        // Populate dropdown options
                        for (var i = 0; i < data.length; i++) {
                            var option = document.createElement('option');
                            option.value = data[i];
                            option.text = data[i];
                            dropdown.appendChild(option);
                        }
                    });
                },
                error: function (error) {
                    console.error('Error fetching fields:', error);
                }
            });
            
        };
    
</script> -->

<!-- FIELD OF THAT MODEL SHOULD COME AS DROPDOWN  -->
<!-- JUGAD -->
<!-- <script>
     document.addEventListener("DOMContentLoaded", function () {
        
        $("#id_para_11").change(function () {
                   document.getElementById('id_para_1').value =this.value;
        })
        $("#id_para_22").change(function () {
                   document.getElementById('id_para_2').value =this.value;
        })
        $("#id_para_33").change(function () {
                   document.getElementById('id_para_3').value =this.value;
        })
        $("#id_para_44").change(function () {
                   document.getElementById('id_para_4').value =this.value;
        })
        $("#id_para_55").change(function () {
                   document.getElementById('id_para_5').value =this.value;
        })});
</script> -->


  
  <div class="container-fluid">
    <div class="row">
      <div class="container-fluid">
          {% if WFList %}
          <br>
          <h3>List of Workflow</h3>
          <div>
            <table class="table table-hover table-responsive-md table-bordered" style="font-size: 10px;">
                <thead>
                  <tr>
                    <th class="custom-th" scope="col">WFID</th>
                    <th class="custom-th" scope="col">AppName</th>
                    <th class="custom-th" scope="col">Process Name</th>
                    <th class="custom-th" scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for wf in WFList %}
                  <tr>
                    <td class="custom-td" scope="row">{{wf.WF_ID}}</td>
                    <td class="custom-td">{{wf.AppName}}</td>
                    <td class="custom-td">{{wf.ProcessName}}</td>
                    <td class="custom-td">
                        <a type="button" class="btn btn-primary" href="{% url 'editworkflow' wf.WF_ID %}" style="padding-left:10px;padding-right: 10px;">Edit</a>
                        
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
            </table>
          <div>
          {% else %}
              <h4 class="text-center alert alert-warning" style="font-size: 14px;">No workflow available</h4>
          {% endif %}
          </div>
      </div>
    </div>
  </div>
{% endblock %}
 


 

workflow/templates/workflow/workflow.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    {{ page_title }}
{% endblock title %}

{% block formcontent %}
{% if form %}
<div class="text-center">
  <h2 style="color:darkcyan;font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;"> {{ app_title }} </h2></div>
<form method="post" id="workflow-form">
    {% csrf_token %}
  
    <div class="row">
      
        <div class="col-md-12 text-left">
          {{ form.ProcessName|as_crispy_field }}
        </div>
        
       </div>
          <div class="row">
          <div class="col-md-6 text-left">
            {{ form.para_1|as_crispy_field }}
          
          </div>
          <div class="col-md-6 text-left">
            {{ form.value_1|as_crispy_field }}
          </div></div>
          
          <div class="row">
            <div class="col-md-6 text-left">
              {{ form.para_2|as_crispy_field }}
             
              
            </div>
            <div class="col-md-6 text-left">
              {{ form.value_2|as_crispy_field }}

            </div></div>
            <div class="row">
                <div class="col-md-6 text-left">
                  {{ form.para_3|as_crispy_field }}
                 
                </div>
                <div class="col-md-6 text-left">
                  {{ form.value_3|as_crispy_field }}
                </div></div>
                <div class="row">
                    <div class="col-md-6 text-left">
                      {{ form.para_4|as_crispy_field }}
                     
                    </div>
                    <div class="col-md-6 text-left">
                      {{ form.value_4|as_crispy_field }}
                    </div></div>
                    <div class="row">
                        <div class="col-md-6 text-left">
                          {{ form.para_5|as_crispy_field }}

                        </div>
                        <div class="col-md-6 text-left">
                          {{ form.value_5|as_crispy_field }}
                        </div></div>
                        <div class="row">
                            <div class="col-6">
                                {{ form.User_names|as_crispy_field }}
                            </div>
                        </div>

    <button type="submit">Submit</button>
  </form>
  {% else %}
    <a type="button" class="btn btn-primary" href="{% url 'addworkflow' %}" style="margin-left:15px;">Create</a>
  {% endif %}

  <div class="container-fluid">
    <div class="row">
      <div class="container-fluid">
          {% if WFList %}
          <br>
          <h3>List of Workflow</h3>
          <div>
            <table class="table table-hover table-responsive-md table-bordered" style="font-size: 10px;">
                <thead>
                  <tr>
                    <th class="custom-th" scope="col">WFID</th>
                    <!-- <th class="custom-th" scope="col">AppName</th> -->
                    <th class="custom-th" scope="col">Process Name</th>
                    <th class="custom-th" scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for wf in WFList %}
                  <tr>
                    <td class="custom-td" scope="row">{{wf.WF_ID}}</td>
                    <!-- <td class="custom-td">{{wf.AppName}}</td> -->
                    <td class="custom-td">{{wf.ProcessName}}</td>
                    <td class="custom-td">
                        <a type="button" class="btn btn-primary" href="{% url 'editworkflow' wf.WF_ID %}" style="padding-left:10px;padding-right: 10px;">Edit</a>
                        
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
            </table>
          <div>
          {% else %}
              <h4 class="text-center alert alert-warning" style="font-size: 14px;">No workflow available</h4>
          {% endif %}
          </div>
      </div>
    </div>
  </div>
{% endblock %}
 


 